import type { MetroProductRecord } from "./metroProductsDb";

/** Catalogue par défaut Metro Séquières Toulouse — chargé automatiquement si aucun fichier local n'existe. */
export const METRO_DEFAULT_CATALOG: MetroProductRecord[] = [
  /* ─────────────────────────────── PAINS ─────────────────────────────── */
  {
    id: "mdc-pain-01",
    nom: "Baguette tradition précuite METRO (lot x60) — 0,31 €/u",
    categorie: "pain",
    prixTotal: 18.50,
    poidsTotal: 60,
    prixParGramme: 0.3083,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-pain-02",
    nom: "Pain de mie sandwich carré METRO (lot x30 tranches) — 0,14 €/u",
    categorie: "pain",
    prixTotal: 4.20,
    poidsTotal: 30,
    prixParGramme: 0.14,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-pain-03",
    nom: "Pain hamburger METRO (lot x48) — 0,20 €/u",
    categorie: "pain",
    prixTotal: 9.80,
    poidsTotal: 48,
    prixParGramme: 0.2042,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-pain-04",
    nom: "Pain hot-dog brioche METRO (lot x60) — 0,21 €/u",
    categorie: "pain",
    prixTotal: 12.40,
    poidsTotal: 60,
    prixParGramme: 0.2067,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-pain-05",
    nom: "Ciabatta METRO (lot x30) — 0,36 €/u",
    categorie: "pain",
    prixTotal: 10.90,
    poidsTotal: 30,
    prixParGramme: 0.3633,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-pain-06",
    nom: "Pain panini METRO (lot x30) — 0,29 €/u",
    categorie: "pain",
    prixTotal: 8.60,
    poidsTotal: 30,
    prixParGramme: 0.2867,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-pain-07",
    nom: "Wrap farine de blé METRO (lot x80) — 0,14 €/u",
    categorie: "pain",
    prixTotal: 11.20,
    poidsTotal: 80,
    prixParGramme: 0.14,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-pain-08",
    nom: "Bun brioche sésame METRO (lot x48) — 0,28 €/u",
    categorie: "pain",
    prixTotal: 13.50,
    poidsTotal: 48,
    prixParGramme: 0.2813,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-pain-09",
    nom: "Pain complet mie carrée METRO (lot x25) — 0,22 €/u",
    categorie: "pain",
    prixTotal: 5.50,
    poidsTotal: 25,
    prixParGramme: 0.22,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-pain-10",
    nom: "Focaccia huile d'olive METRO (lot x20) — 0,55 €/u",
    categorie: "pain",
    prixTotal: 11.00,
    poidsTotal: 20,
    prixParGramme: 0.55,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-pain-11",
    nom: "Pain pita METRO (lot x50) — 0,18 €/u",
    categorie: "pain",
    prixTotal: 9.00,
    poidsTotal: 50,
    prixParGramme: 0.18,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-pain-12",
    nom: "Pain de campagne tranché METRO (sachet 500g) — 8,40 €/kg",
    categorie: "pain",
    prixTotal: 4.20,
    poidsTotal: 500,
    prixParGramme: 0.0084,
    modeTarif: "gramme",
    vegetarien: true,
  },

  /* ─────────────────────────────── VIANDES ─────────────────────────────── */
  {
    id: "mdc-viande-01",
    nom: "Jambon cuit supérieur FLEURY MICHON (2kg) — 8,40 €/kg",
    categorie: "viande",
    prixTotal: 16.80,
    poidsTotal: 2000,
    prixParGramme: 0.0084,
    modeTarif: "gramme",
    vegetarien: false,
  },
  {
    id: "mdc-viande-02",
    nom: "Blanc de poulet tranché METRO Chef (1kg) — 9,90 €/kg",
    categorie: "viande",
    prixTotal: 9.90,
    poidsTotal: 1000,
    prixParGramme: 0.0099,
    modeTarif: "gramme",
    vegetarien: false,
  },
  {
    id: "mdc-viande-03",
    nom: "Escalope de dinde nature METRO (1kg) — 8,40 €/kg",
    categorie: "viande",
    prixTotal: 8.40,
    poidsTotal: 1000,
    prixParGramme: 0.0084,
    modeTarif: "gramme",
    vegetarien: false,
  },
  {
    id: "mdc-viande-04",
    nom: "Steak haché 15% MG METRO Chef (10x100g) — 12,60 €/kg",
    categorie: "viande",
    prixTotal: 12.60,
    poidsTotal: 1000,
    prixParGramme: 0.0126,
    modeTarif: "gramme",
    vegetarien: false,
  },
  {
    id: "mdc-viande-05",
    nom: "Thon entier au naturel BELLE FRANCE (boîte 1/2 x12, 150g égouttés) — 12,44 €/kg",
    categorie: "viande",
    prixTotal: 22.40,
    poidsTotal: 1800,
    prixParGramme: 0.01244,
    modeTarif: "gramme",
    vegetarien: false,
  },
  {
    id: "mdc-viande-06",
    nom: "Lardons fumés METRO (sachet 1kg) — 7,20 €/kg",
    categorie: "viande",
    prixTotal: 7.20,
    poidsTotal: 1000,
    prixParGramme: 0.0072,
    modeTarif: "gramme",
    vegetarien: false,
  },
  {
    id: "mdc-viande-07",
    nom: "Jambon de Bayonne tranché METRO (500g) — 19,60 €/kg",
    categorie: "viande",
    prixTotal: 9.80,
    poidsTotal: 500,
    prixParGramme: 0.0196,
    modeTarif: "gramme",
    vegetarien: false,
  },
  {
    id: "mdc-viande-08",
    nom: "Chorizo tranché fort METRO (1kg) — 11,50 €/kg",
    categorie: "viande",
    prixTotal: 11.50,
    poidsTotal: 1000,
    prixParGramme: 0.0115,
    modeTarif: "gramme",
    vegetarien: false,
  },
  {
    id: "mdc-viande-09",
    nom: "Merguez bœuf/mouton METRO (1kg) — 8,90 €/kg",
    categorie: "viande",
    prixTotal: 8.90,
    poidsTotal: 1000,
    prixParGramme: 0.0089,
    modeTarif: "gramme",
    vegetarien: false,
  },
  {
    id: "mdc-viande-10",
    nom: "Saumon fumé METRO (500g) — 29,80 €/kg",
    categorie: "viande",
    prixTotal: 14.90,
    poidsTotal: 500,
    prixParGramme: 0.0298,
    modeTarif: "gramme",
    vegetarien: false,
  },
  {
    id: "mdc-viande-11",
    nom: "Blanc de dinde rôti tranché METRO Chef (1kg) — 9,40 €/kg",
    categorie: "viande",
    prixTotal: 9.40,
    poidsTotal: 1000,
    prixParGramme: 0.0094,
    modeTarif: "gramme",
    vegetarien: false,
  },
  {
    id: "mdc-viande-12",
    nom: "Rosette de Lyon METRO (1kg) — 12,80 €/kg",
    categorie: "viande",
    prixTotal: 12.80,
    poidsTotal: 1000,
    prixParGramme: 0.0128,
    modeTarif: "gramme",
    vegetarien: false,
  },
  {
    id: "mdc-viande-13",
    nom: "Mortadelle tranchée METRO (1kg) — 7,80 €/kg",
    categorie: "viande",
    prixTotal: 7.80,
    poidsTotal: 1000,
    prixParGramme: 0.0078,
    modeTarif: "gramme",
    vegetarien: false,
  },
  {
    id: "mdc-viande-14",
    nom: "Poulet grillé mariné tranché METRO (1kg) — 11,20 €/kg",
    categorie: "viande",
    prixTotal: 11.20,
    poidsTotal: 1000,
    prixParGramme: 0.0112,
    modeTarif: "gramme",
    vegetarien: false,
  },
  {
    id: "mdc-viande-15",
    nom: "Cuisse de poulet désossée METRO (sac 2kg) — 5,20 €/kg",
    categorie: "viande",
    prixTotal: 10.40,
    poidsTotal: 2000,
    prixParGramme: 0.0052,
    modeTarif: "gramme",
    vegetarien: false,
  },
  {
    id: "mdc-viande-16",
    nom: "Jambon cuit Paris METRO (1kg tranché) — 9,60 €/kg",
    categorie: "viande",
    prixTotal: 9.60,
    poidsTotal: 1000,
    prixParGramme: 0.0096,
    modeTarif: "gramme",
    vegetarien: false,
  },
  {
    id: "mdc-viande-17",
    nom: "Aiguillettes de canard METRO (500g) — 18,00 €/kg",
    categorie: "viande",
    prixTotal: 9.00,
    poidsTotal: 500,
    prixParGramme: 0.018,
    modeTarif: "gramme",
    vegetarien: false,
  },
  {
    id: "mdc-viande-18",
    nom: "Salami Milano tranché METRO (1kg) — 13,40 €/kg",
    categorie: "viande",
    prixTotal: 13.40,
    poidsTotal: 1000,
    prixParGramme: 0.0134,
    modeTarif: "gramme",
    vegetarien: false,
  },
  {
    id: "mdc-viande-19",
    nom: "Rôti de porc cuit METRO (1kg) — 10,80 €/kg",
    categorie: "viande",
    prixTotal: 10.80,
    poidsTotal: 1000,
    prixParGramme: 0.0108,
    modeTarif: "gramme",
    vegetarien: false,
  },
  {
    id: "mdc-viande-20",
    nom: "Bresaola tranchée METRO (500g) — 24,00 €/kg",
    categorie: "viande",
    prixTotal: 12.00,
    poidsTotal: 500,
    prixParGramme: 0.024,
    modeTarif: "gramme",
    vegetarien: false,
  },

  /* ─────────────────── PROTÉINES VÉGÉTARIENNES ─────────────────── */
  {
    id: "mdc-veg-01",
    nom: "Falafel METRO (sac 1kg surgelé) — 6,80 €/kg",
    categorie: "proteine_vegetarienne",
    prixTotal: 6.80,
    poidsTotal: 1000,
    prixParGramme: 0.0068,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-veg-02",
    nom: "Galettes de légumes METRO (sac 1kg surgelé) — 7,40 €/kg",
    categorie: "proteine_vegetarienne",
    prixTotal: 7.40,
    poidsTotal: 1000,
    prixParGramme: 0.0074,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-veg-03",
    nom: "Steak végétal soja METRO (10x90g) — 10,22 €/kg",
    categorie: "proteine_vegetarienne",
    prixTotal: 9.20,
    poidsTotal: 900,
    prixParGramme: 0.01022,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-veg-04",
    nom: "Œufs frais calibre M METRO (boîte x30) — 0,19 €/u",
    categorie: "proteine_vegetarienne",
    prixTotal: 5.60,
    poidsTotal: 30,
    prixParGramme: 0.1867,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-veg-05",
    nom: "Tofu ferme nature METRO (1kg) — 6,40 €/kg",
    categorie: "proteine_vegetarienne",
    prixTotal: 6.40,
    poidsTotal: 1000,
    prixParGramme: 0.0064,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-veg-06",
    nom: "Galette quinoa légumes METRO (sac 1kg surgelé) — 8,60 €/kg",
    categorie: "proteine_vegetarienne",
    prixTotal: 8.60,
    poidsTotal: 1000,
    prixParGramme: 0.0086,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-veg-07",
    nom: "Seitan tranché METRO (500g) — 15,60 €/kg",
    categorie: "proteine_vegetarienne",
    prixTotal: 7.80,
    poidsTotal: 500,
    prixParGramme: 0.0156,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-veg-08",
    nom: "Halloumi grillé METRO (250g) — 28,00 €/kg",
    categorie: "proteine_vegetarienne",
    prixTotal: 7.00,
    poidsTotal: 250,
    prixParGramme: 0.028,
    modeTarif: "gramme",
    vegetarien: true,
  },

  /* ─────────────────────────────── FROMAGES ─────────────────────────────── */
  {
    id: "mdc-fromage-01",
    nom: "Emmental râpé METRO Chef (1kg) — 8,90 €/kg",
    categorie: "fromage",
    prixTotal: 8.90,
    poidsTotal: 1000,
    prixParGramme: 0.0089,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-fromage-02",
    nom: "Mozzarella fior di latte METRO (boule 125g x12) — 9,60 €/kg",
    categorie: "fromage",
    prixTotal: 14.40,
    poidsTotal: 1500,
    prixParGramme: 0.0096,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-fromage-03",
    nom: "Cheddar tranché METRO (1kg) — 10,20 €/kg",
    categorie: "fromage",
    prixTotal: 10.20,
    poidsTotal: 1000,
    prixParGramme: 0.0102,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-fromage-04",
    nom: "Comté AOP tranché METRO (1kg) — 16,50 €/kg",
    categorie: "fromage",
    prixTotal: 16.50,
    poidsTotal: 1000,
    prixParGramme: 0.0165,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-fromage-05",
    nom: "Brie de Meaux METRO (~1,2kg) — 10,67 €/kg",
    categorie: "fromage",
    prixTotal: 12.80,
    poidsTotal: 1200,
    prixParGramme: 0.01067,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-fromage-06",
    nom: "Chèvre bûche METRO (colis 6x150g) — 10,67 €/kg",
    categorie: "fromage",
    prixTotal: 9.60,
    poidsTotal: 900,
    prixParGramme: 0.01067,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-fromage-07",
    nom: "Raclette tranchée METRO (1kg) — 11,90 €/kg",
    categorie: "fromage",
    prixTotal: 11.90,
    poidsTotal: 1000,
    prixParGramme: 0.0119,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-fromage-08",
    nom: "Gouda tranché METRO (1kg) — 9,80 €/kg",
    categorie: "fromage",
    prixTotal: 9.80,
    poidsTotal: 1000,
    prixParGramme: 0.0098,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-fromage-09",
    nom: "Emmental tranché METRO Chef (1,6kg) — 8,50 €/kg",
    categorie: "fromage",
    prixTotal: 13.60,
    poidsTotal: 1600,
    prixParGramme: 0.0085,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-fromage-10",
    nom: "Feta AOP METRO (bloc 400g saumure) — 17,25 €/kg",
    categorie: "fromage",
    prixTotal: 6.90,
    poidsTotal: 400,
    prixParGramme: 0.01725,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-fromage-11",
    nom: "Parmesan râpé METRO (sachet 500g) — 19,80 €/kg",
    categorie: "fromage",
    prixTotal: 9.90,
    poidsTotal: 500,
    prixParGramme: 0.0198,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-fromage-12",
    nom: "Camembert au lait pasteurisé METRO (250g x4) — 13,60 €/kg",
    categorie: "fromage",
    prixTotal: 13.60,
    poidsTotal: 1000,
    prixParGramme: 0.0136,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-fromage-13",
    nom: "Roquefort AOP METRO (150g) — 29,33 €/kg",
    categorie: "fromage",
    prixTotal: 4.40,
    poidsTotal: 150,
    prixParGramme: 0.02933,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-fromage-14",
    nom: "Mozzarella râpée pizza METRO (2,5kg) — 7,80 €/kg",
    categorie: "fromage",
    prixTotal: 19.50,
    poidsTotal: 2500,
    prixParGramme: 0.0078,
    modeTarif: "gramme",
    vegetarien: true,
  },

  /* ─────────────────────────────── SAUCES ─────────────────────────────── */
  {
    id: "mdc-sauce-01",
    nom: "Mayonnaise METRO Chef (seau 5L) — 2,36 €/kg",
    categorie: "sauce",
    prixTotal: 11.80,
    poidsTotal: 5000,
    prixParGramme: 0.00236,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-sauce-02",
    nom: "Ketchup HEINZ (seau 5kg) — 2,68 €/kg",
    categorie: "sauce",
    prixTotal: 13.40,
    poidsTotal: 5000,
    prixParGramme: 0.00268,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-sauce-03",
    nom: "Moutarde de Dijon METRO (seau 5kg) — 1,84 €/kg",
    categorie: "sauce",
    prixTotal: 9.20,
    poidsTotal: 5000,
    prixParGramme: 0.00184,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-sauce-04",
    nom: "Sauce Caesar METRO (bidon 2,5L) — 3,56 €/kg",
    categorie: "sauce",
    prixTotal: 8.90,
    poidsTotal: 2500,
    prixParGramme: 0.00356,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-sauce-05",
    nom: "Sauce barbecue METRO (bidon 2,5L) — 3,04 €/kg",
    categorie: "sauce",
    prixTotal: 7.60,
    poidsTotal: 2500,
    prixParGramme: 0.00304,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-sauce-06",
    nom: "Harissa METRO (boîte 5kg) — 1,62 €/kg",
    categorie: "sauce",
    prixTotal: 8.10,
    poidsTotal: 5000,
    prixParGramme: 0.00162,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-sauce-07",
    nom: "Sauce burger METRO (bidon 2,5L) — 3,28 €/kg",
    categorie: "sauce",
    prixTotal: 8.20,
    poidsTotal: 2500,
    prixParGramme: 0.00328,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-sauce-08",
    nom: "Pesto alla genovese METRO (bocal 1kg) — 7,40 €/kg",
    categorie: "sauce",
    prixTotal: 7.40,
    poidsTotal: 1000,
    prixParGramme: 0.0074,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-sauce-09",
    nom: "Sauce tzatziki METRO (1kg) — 5,80 €/kg",
    categorie: "sauce",
    prixTotal: 5.80,
    poidsTotal: 1000,
    prixParGramme: 0.0058,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-sauce-10",
    nom: "Sauce andalouse METRO (bidon 2,5L) — 3,40 €/kg",
    categorie: "sauce",
    prixTotal: 8.50,
    poidsTotal: 2500,
    prixParGramme: 0.0034,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-sauce-11",
    nom: "Sauce sriracha METRO (flacon 1L) — 6,40 €/kg",
    categorie: "sauce",
    prixTotal: 6.40,
    poidsTotal: 1000,
    prixParGramme: 0.0064,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-sauce-12",
    nom: "Houmous METRO (pot 1kg) — 5,80 €/kg",
    categorie: "sauce",
    prixTotal: 5.80,
    poidsTotal: 1000,
    prixParGramme: 0.0058,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-sauce-13",
    nom: "Beurre doux METRO (plaque 1kg) — 6,20 €/kg",
    categorie: "sauce",
    prixTotal: 6.20,
    poidsTotal: 1000,
    prixParGramme: 0.0062,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-sauce-14",
    nom: "Crème fraîche épaisse METRO (seau 5kg) — 2,92 €/kg",
    categorie: "sauce",
    prixTotal: 14.60,
    poidsTotal: 5000,
    prixParGramme: 0.00292,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-sauce-15",
    nom: "Vinaigrette classique METRO (bidon 2,5L) — 2,96 €/kg",
    categorie: "sauce",
    prixTotal: 7.40,
    poidsTotal: 2500,
    prixParGramme: 0.00296,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-sauce-16",
    nom: "Sauce tartare METRO (bidon 2,5L) — 3,60 €/kg",
    categorie: "sauce",
    prixTotal: 9.00,
    poidsTotal: 2500,
    prixParGramme: 0.0036,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-sauce-17",
    nom: "Tapenade olive noire METRO (bocal 1kg) — 8,40 €/kg",
    categorie: "sauce",
    prixTotal: 8.40,
    poidsTotal: 1000,
    prixParGramme: 0.0084,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-sauce-18",
    nom: "Sauce aigre-douce METRO (bidon 2,5L) — 3,20 €/kg",
    categorie: "sauce",
    prixTotal: 8.00,
    poidsTotal: 2500,
    prixParGramme: 0.0032,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-sauce-19",
    nom: "Guacamole METRO (pot 1kg) — 9,80 €/kg",
    categorie: "sauce",
    prixTotal: 9.80,
    poidsTotal: 1000,
    prixParGramme: 0.0098,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-sauce-20",
    nom: "Sauce bolognaise METRO Chef (boîte 5/1, 5kg) — 2,64 €/kg",
    categorie: "sauce",
    prixTotal: 13.20,
    poidsTotal: 5000,
    prixParGramme: 0.00264,
    modeTarif: "gramme",
    vegetarien: false,
  },

  /* ─────────────────────────────── LÉGUMES ─────────────────────────────── */
  {
    id: "mdc-legume-01",
    nom: "Laitue iceberg prête emploi METRO (sachet 1kg) — 3,20 €/kg",
    categorie: "legumes",
    prixTotal: 3.20,
    poidsTotal: 1000,
    prixParGramme: 0.0032,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-legume-02",
    nom: "Tomates rondes METRO (plateau 6kg) — 1,63 €/kg",
    categorie: "legumes",
    prixTotal: 9.80,
    poidsTotal: 6000,
    prixParGramme: 0.001633,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-legume-03",
    nom: "Cornichons entiers aigre-doux METRO (boîte 4/4, 850g égouttés) — 5,41 €/kg",
    categorie: "legumes",
    prixTotal: 4.60,
    poidsTotal: 850,
    prixParGramme: 0.005412,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-legume-04",
    nom: "Oignons émincés surgelés METRO (sac 1kg) — 2,10 €/kg",
    categorie: "legumes",
    prixTotal: 2.10,
    poidsTotal: 1000,
    prixParGramme: 0.0021,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-legume-05",
    nom: "Poivrons rouges METRO (colis 5kg) — 1,68 €/kg",
    categorie: "legumes",
    prixTotal: 8.40,
    poidsTotal: 5000,
    prixParGramme: 0.00168,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-legume-06",
    nom: "Roquette METRO (sachet 500g) — 7,60 €/kg",
    categorie: "legumes",
    prixTotal: 3.80,
    poidsTotal: 500,
    prixParGramme: 0.0076,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-legume-07",
    nom: "Avocat METRO (plateau x12, ~200g/u) — 4,67 €/kg",
    categorie: "legumes",
    prixTotal: 11.20,
    poidsTotal: 2400,
    prixParGramme: 0.004667,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-legume-08",
    nom: "Concombre METRO (colis 6kg) — 0,93 €/kg",
    categorie: "legumes",
    prixTotal: 5.60,
    poidsTotal: 6000,
    prixParGramme: 0.000933,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-legume-09",
    nom: "Champignons Paris émincés METRO (boîte 1/2 x12) — 6,32 €/kg",
    categorie: "legumes",
    prixTotal: 14.40,
    poidsTotal: 2280,
    prixParGramme: 0.006316,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-legume-10",
    nom: "Tomates séchées à l'huile METRO (bocal 1kg) — 8,60 €/kg",
    categorie: "legumes",
    prixTotal: 8.60,
    poidsTotal: 1000,
    prixParGramme: 0.0086,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-legume-11",
    nom: "Tomates cerises METRO (barquette 500g) — 7,80 €/kg",
    categorie: "legumes",
    prixTotal: 3.90,
    poidsTotal: 500,
    prixParGramme: 0.0078,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-legume-12",
    nom: "Épinards frais METRO (sachet 1kg) — 4,20 €/kg",
    categorie: "legumes",
    prixTotal: 4.20,
    poidsTotal: 1000,
    prixParGramme: 0.0042,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-legume-13",
    nom: "Poivrons grillés à l'huile METRO (bocal 1kg) — 7,20 €/kg",
    categorie: "legumes",
    prixTotal: 7.20,
    poidsTotal: 1000,
    prixParGramme: 0.0072,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-legume-14",
    nom: "Olives noires dénoyautées METRO (boîte 2kg) — 4,90 €/kg",
    categorie: "legumes",
    prixTotal: 9.80,
    poidsTotal: 2000,
    prixParGramme: 0.0049,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-legume-15",
    nom: "Maïs en grains METRO (boîte 1/2 x12, 200g égouttés) — 4,50 €/kg",
    categorie: "legumes",
    prixTotal: 10.80,
    poidsTotal: 2400,
    prixParGramme: 0.0045,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-legume-16",
    nom: "Salade mélangée METRO (sachet 500g) — 9,20 €/kg",
    categorie: "legumes",
    prixTotal: 4.60,
    poidsTotal: 500,
    prixParGramme: 0.0092,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-legume-17",
    nom: "Olives vertes farcies piment METRO (boîte 1kg) — 6,80 €/kg",
    categorie: "legumes",
    prixTotal: 6.80,
    poidsTotal: 1000,
    prixParGramme: 0.0068,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-legume-18",
    nom: "Oignons nouveaux METRO (botte 500g) — 4,80 €/kg",
    categorie: "legumes",
    prixTotal: 2.40,
    poidsTotal: 500,
    prixParGramme: 0.0048,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-legume-19",
    nom: "Betterave cuite sous vide METRO (sachet 1kg) — 2,80 €/kg",
    categorie: "legumes",
    prixTotal: 2.80,
    poidsTotal: 1000,
    prixParGramme: 0.0028,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-legume-20",
    nom: "Carottes râpées METRO (sachet 1kg) — 3,40 €/kg",
    categorie: "legumes",
    prixTotal: 3.40,
    poidsTotal: 1000,
    prixParGramme: 0.0034,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-legume-21",
    nom: "Câpres au vinaigre METRO (bocal 500g) — 9,60 €/kg",
    categorie: "legumes",
    prixTotal: 4.80,
    poidsTotal: 500,
    prixParGramme: 0.0096,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-legume-22",
    nom: "Poivrons multicolores grillés METRO (bocal 1,7kg) — 5,41 €/kg",
    categorie: "legumes",
    prixTotal: 9.20,
    poidsTotal: 1700,
    prixParGramme: 0.00541,
    modeTarif: "gramme",
    vegetarien: true,
  },
  {
    id: "mdc-legume-23",
    nom: "Artichauds à l'huile METRO (bocal 800g) — 9,88 €/kg",
    categorie: "legumes",
    prixTotal: 7.90,
    poidsTotal: 800,
    prixParGramme: 0.009875,
    modeTarif: "gramme",
    vegetarien: true,
  },

  /* ─────────────────────────────── BOISSONS ─────────────────────────────── */
  {
    id: "mdc-boisson-01",
    nom: "Coca-Cola 33cl (pack x24) — 0,60 €/u",
    categorie: "boisson",
    prixTotal: 14.40,
    poidsTotal: 24,
    prixParGramme: 0.6,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-boisson-02",
    nom: "Coca-Cola Zero 33cl (pack x24) — 0,60 €/u",
    categorie: "boisson",
    prixTotal: 14.40,
    poidsTotal: 24,
    prixParGramme: 0.6,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-boisson-03",
    nom: "Fanta Orange 33cl (pack x24) — 0,55 €/u",
    categorie: "boisson",
    prixTotal: 13.20,
    poidsTotal: 24,
    prixParGramme: 0.55,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-boisson-04",
    nom: "Sprite 33cl (pack x24) — 0,55 €/u",
    categorie: "boisson",
    prixTotal: 13.20,
    poidsTotal: 24,
    prixParGramme: 0.55,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-boisson-05",
    nom: "Eau minérale CRISTALINE 50cl (pack x24) — 0,20 €/u",
    categorie: "boisson",
    prixTotal: 4.80,
    poidsTotal: 24,
    prixParGramme: 0.2,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-boisson-06",
    nom: "Eau gazeuse PERRIER 33cl (pack x24) — 0,45 €/u",
    categorie: "boisson",
    prixTotal: 10.80,
    poidsTotal: 24,
    prixParGramme: 0.45,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-boisson-07",
    nom: "Jus multifruits METRO (brique 1L x6) — 1,20 €/u",
    categorie: "boisson",
    prixTotal: 7.20,
    poidsTotal: 6,
    prixParGramme: 1.2,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-boisson-08",
    nom: "Ice Tea pêche LIPTON 33cl (pack x24) — 0,50 €/u",
    categorie: "boisson",
    prixTotal: 12.00,
    poidsTotal: 24,
    prixParGramme: 0.5,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-boisson-09",
    nom: "Red Bull 25cl METRO (pack x24) — 1,20 €/u",
    categorie: "boisson",
    prixTotal: 28.80,
    poidsTotal: 24,
    prixParGramme: 1.2,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-boisson-10",
    nom: "Oasis tropical 33cl (pack x24) — 0,48 €/u",
    categorie: "boisson",
    prixTotal: 11.52,
    poidsTotal: 24,
    prixParGramme: 0.48,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-boisson-11",
    nom: "Jus d'orange pur jus TROPICANA 1L (pack x6) — 1,90 €/u",
    categorie: "boisson",
    prixTotal: 11.40,
    poidsTotal: 6,
    prixParGramme: 1.9,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-boisson-12",
    nom: "Peroni 33cl (pack x24) — 0,90 €/u",
    categorie: "boisson",
    prixTotal: 21.60,
    poidsTotal: 24,
    prixParGramme: 0.9,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-boisson-13",
    nom: "Limonade LORINA 75cl (caisse x12) — 1,42 €/u",
    categorie: "boisson",
    prixTotal: 17.00,
    poidsTotal: 12,
    prixParGramme: 1.4167,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-boisson-14",
    nom: "Eau EVIAN 50cl (pack x24) — 0,37 €/u",
    categorie: "boisson",
    prixTotal: 8.90,
    poidsTotal: 24,
    prixParGramme: 0.3708,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-boisson-15",
    nom: "Schweppes Agrum 33cl (pack x24) — 0,52 €/u",
    categorie: "boisson",
    prixTotal: 12.50,
    poidsTotal: 24,
    prixParGramme: 0.5208,
    modeTarif: "unite",
    vegetarien: true,
  },

  /* ─────────────────────────────── DESSERTS ─────────────────────────────── */
  {
    id: "mdc-dessert-01",
    nom: "Cookies chocolat METRO (boîte x20) — 0,34 €/u",
    categorie: "dessert",
    prixTotal: 6.80,
    poidsTotal: 20,
    prixParGramme: 0.34,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-dessert-02",
    nom: "Brownie individuel METRO (boîte x18) — 0,55 €/u",
    categorie: "dessert",
    prixTotal: 9.90,
    poidsTotal: 18,
    prixParGramme: 0.55,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-dessert-03",
    nom: "Madeleine individuelle METRO (sachet x40) — 0,18 €/u",
    categorie: "dessert",
    prixTotal: 7.20,
    poidsTotal: 40,
    prixParGramme: 0.18,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-dessert-04",
    nom: "Yaourt brassé nature METRO (pot 125g x16) — 0,35 €/u",
    categorie: "dessert",
    prixTotal: 5.60,
    poidsTotal: 16,
    prixParGramme: 0.35,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-dessert-05",
    nom: "Mousse au chocolat METRO (coupelle 60g x12) — 0,53 €/u",
    categorie: "dessert",
    prixTotal: 6.40,
    poidsTotal: 12,
    prixParGramme: 0.5333,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-dessert-06",
    nom: "Crème brûlée individuelle METRO (pot 100g x12) — 0,80 €/u",
    categorie: "dessert",
    prixTotal: 9.60,
    poidsTotal: 12,
    prixParGramme: 0.8,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-dessert-07",
    nom: "Tiramisu individuel METRO (100g x12) — 0,90 €/u",
    categorie: "dessert",
    prixTotal: 10.80,
    poidsTotal: 12,
    prixParGramme: 0.9,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-dessert-08",
    nom: "Tarte au citron individuelle METRO (x12) — 1,00 €/u",
    categorie: "dessert",
    prixTotal: 12.00,
    poidsTotal: 12,
    prixParGramme: 1.0,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-dessert-09",
    nom: "Panna cotta coulis framboise METRO (x12) — 0,90 €/u",
    categorie: "dessert",
    prixTotal: 10.80,
    poidsTotal: 12,
    prixParGramme: 0.9,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-dessert-10",
    nom: "Tarte aux pommes individuelle METRO (x12) — 0,83 €/u",
    categorie: "dessert",
    prixTotal: 10.00,
    poidsTotal: 12,
    prixParGramme: 0.8333,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-dessert-11",
    nom: "Fondant au chocolat METRO (x12) — 1,10 €/u",
    categorie: "dessert",
    prixTotal: 13.20,
    poidsTotal: 12,
    prixParGramme: 1.1,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-dessert-12",
    nom: "Fruit de saison portion METRO (plateau x12) — 0,70 €/u",
    categorie: "dessert",
    prixTotal: 8.40,
    poidsTotal: 12,
    prixParGramme: 0.7,
    modeTarif: "unite",
    vegetarien: true,
  },

  /* ─────────────────────────────── EMBALLAGES ─────────────────────────────── */
  {
    id: "mdc-emb-01",
    nom: "Sac kraft sandwich METRO (lot x500) — 0,025 €/u",
    categorie: "emballage",
    prixTotal: 12.50,
    poidsTotal: 500,
    prixParGramme: 0.025,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-emb-02",
    nom: "Papier sulfurisé sandwich METRO (lot x500 feuilles) — 0,018 €/u",
    categorie: "emballage",
    prixTotal: 8.90,
    poidsTotal: 500,
    prixParGramme: 0.0178,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-emb-03",
    nom: "Serviettes papier 33x33 METRO (lot x500) — 0,008 €/u",
    categorie: "emballage",
    prixTotal: 4.20,
    poidsTotal: 500,
    prixParGramme: 0.0084,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-emb-04",
    nom: "Barquette carton burger METRO (lot x200) — 0,074 €/u",
    categorie: "emballage",
    prixTotal: 14.80,
    poidsTotal: 200,
    prixParGramme: 0.074,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-emb-05",
    nom: "Boîte carton sandwich triangulaire METRO (lot x100) — 0,162 €/u",
    categorie: "emballage",
    prixTotal: 16.20,
    poidsTotal: 100,
    prixParGramme: 0.162,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-emb-06",
    nom: "Couverts jetables METRO set x100 (couteau+fourchette+serviette) — 0,068 €/u",
    categorie: "emballage",
    prixTotal: 6.80,
    poidsTotal: 100,
    prixParGramme: 0.068,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-emb-07",
    nom: "Sac plastique 26x36cm METRO (lot x1000) — 0,010 €/u",
    categorie: "emballage",
    prixTotal: 9.60,
    poidsTotal: 1000,
    prixParGramme: 0.0096,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-emb-08",
    nom: "Film alimentaire METRO (rouleau 300m x45cm) — 0,008 €/m",
    categorie: "emballage",
    prixTotal: 11.40,
    poidsTotal: 1500,
    prixParGramme: 0.0076,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-emb-09",
    nom: "Boîte salade kraft METRO (lot x150) — 0,12 €/u",
    categorie: "emballage",
    prixTotal: 18.00,
    poidsTotal: 150,
    prixParGramme: 0.12,
    modeTarif: "unite",
    vegetarien: true,
  },
  {
    id: "mdc-emb-10",
    nom: "Gobelets carton 20cl METRO (lot x1000) — 0,062 €/u",
    categorie: "emballage",
    prixTotal: 62.00,
    poidsTotal: 1000,
    prixParGramme: 0.062,
    modeTarif: "unite",
    vegetarien: true,
  },
];
